### ISSUE TITLE
Tests: print seed when tests fail

### ISSUE THREAD

**Issue by jromero** [MerosCrypto/Meros#112]
In tests where randomization is used, the seed used in that test should be printed when the test fails. This would enable reproducibility for potentially flaky tests.

NOTE: Not directly dependent, but would be easier to implement after #108 is merged. We could then leverage [`checkpoint(string)`](https://stefantalpalaru.github.io/nim-unittest2/unittest2.html#checkpoint%2Cstring) from unittest2.

**Comment by kayabaNerve** [comment]
Issue #111 must be fixed before this can be done, right?

**Comment by jromero** [comment]
Yes it should. Hope would be to get both this issue and #111 in one PR.
