### ISSUE TITLE
Unneeded dependency.

### ISSUE THREAD

**Issue by kayabaNerve** [MerosCrypto/Meros#113]
unittest2 was chosen over unittest for its thread support. That said, we can't use its threaded test models (even with macros adding gcsafe to every test) as Nim classifies the code as unsafe. As far as I can tell, it's an issue with the generated code, not our code. It also suffers from deadlocking issues (https://github.com/nim-lang/Nim/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+threadpool).

Due to these issues, we should be able to use the standard unittest which is shipped as part of the standard lib. That makes the unittest2 dependency pointless.

Tagging @jromero as he was the one who moved our tests to a proper framework.

**Comment by jromero** [comment]
Agreed with the overall choice at this point. It's unfortunate that this limitations are present but at this time unittest2 is unnecessary.
