### ISSUE TITLE
Meros crashes at some point in relation to creating a socket.

### ISSUE THREAD

**Issue by kayabaNerve** [MerosCrypto/Meros#141]
```
/home/lukep/Meros/src/Meros.nim(37) Meros
/home/lukep/Meros/src/Meros.nim(32) main
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncdispatch.nim(1874) runForever
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncdispatch.nim(1569) poll
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncdispatch.nim(1335) runOnce
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncdispatch.nim(210) processPendingCallbacks
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncfutures.nim(297) :anonymous
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncnet.nim(462) :anonymous
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncnet.nim(146) newAsyncSocket
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/nativesockets.nim(579) setBlocking
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/includes/oserr.nim(94) raiseOSError
Error: unhandled exception: Bad file descriptor [OSError]
```

This was immediately after a disconnect but meaningfully after multiple "Handling Client connection"s.

**Comment by kayabaNerve** [comment]
This crashed every DT3 seed node without either of the above network messages.

**Comment by kayabaNerve** [comment]
Another after "Accepting".

**Comment by kayabaNerve** [comment]
This is a TOCTOU. Due to how Nim handles async, the only way to catch this error is to try/catch runForever. That would drop all async operations and not allow safe continuation of the program.

I used:
```
from PythonTests.Meros.Meros import Meros, MerosSocket
from PythonTests.Classes.Merit.Blockchain import Blockchain

blockchain = Blockchain()
s = 0
while True:
    live = MerosSocket(5132, 254, 254, True, blockchain.blocks[0].header.hash)
    sync = MerosSocket(5132, 254, 254, False, blockchain.blocks[0].header.hash)

    s += 1
    if s % 10 == 0:
        print(s)

    live.connection.close()
    sync.connection.close()
```
to test this.

It didn't crash on debug, or with strace, as those provided enough time for Nim to lose the race it never should've entered.

I tried writing a MRE in Nim yet was unable to. It's some quirk about Meros that's causing this problem to act up. Unable to submit an issue, our options become:
- Ditch asyncnet.
- Find out Meros's quirk and fix that.
- Ship in debug as that should stop the issue from occurring in most cases.

The first is a humongous effort not possible before mainnet. I'm not sure the second is possible. The third takes the least effort, and is acceptable, for now. It isn't acceptable in the long run.

Meros will now compile in debug mode. This won't be marked fixed, yet will be removed from the DT4 milestone.

**Comment by kayabaNerve** [comment]
If we ditch asyncnet, I'd currently recommend moving to https://github.com/status-im/nim-chronos. It's a bit rougher, yet was built to solve problems with asyncdispatch. It also has the relevant networking functions and hasn't been afraid to improve, even with breaking changes (which is good since we can specify which version to use; we have the ability to lock to an API, yet aren't forced to).

**Comment by kayabaNerve** [comment]
This has been added to the DT4S milestone, representing the move to Nim-Chronos from asyncdispatch/asyncnet. If that doesn't fix this issue, Meros will be kept in debug and removed from this milestone.

**Comment by dom96** [comment]
Well, I tried to reproduce this, but sadly I couldn't even get `cmake` installed on my macOS machine so I'll have to bow out. Sorry about that.

That being said:

> This is a TOCTOU. Due to how Nim handles async, the only way to catch this error is to try/catch runForever. That would drop all async operations and not allow safe continuation of the program.

I think you're wrong here. The exception is raised by `newAsyncSocket`, you should be able to catch that. It doesn't matter if the code path comes from a callback, you can still catch exceptions inside any function (even if it's async). The only exceptions you cannot catch are ones that are truly thrown by the async event loop (these should be rare and if they exist we should fix them).

**Comment by kayabaNerve** [comment]
dom96: Thanks for trying. I didn't expect anything to happen due to the complexity of it.

The code block is:
```
while not server.isClosed():
    try:
        something(await server.accept())
    except Exception:
        continue
```

So yes, async errors are generally catchable, yet this one isn't. I did successfully manage to catch it, but only by wrapping runForever in a try/catch.

**Comment by kayabaNerve** [comment]
This may or may not be fixed in the chronos branch. It adds several close statements to errored sockets and stops the socket overwriting that was happening as part of https://github.com/MerosCrypto/Meros/issues/159. That said, due to the same issue, I can't currently test it. I just wanted to note the progress.

**Comment by kayabaNerve** [comment]
@dom96 I think I found the problem. It's in my "safeClose" function.

```
#Safely close a socket.
proc safeClose*(
    socket: StreamTransport,
    reason: string
) {.forceCheck: [].} =
    if socket.isNil:
        return

    try:
        socket.close()
    except Exception:
        discard

    if reason != "":
        logDebug "Closing raw socket", reason = reason
```

I'm double closing a socket which has its FD reused by the new connection. It's not explicitly a problem in asyncnet (except for the fact it bubbles up through runForever). If anything, it'd be a feature request for RAII or a flag to not attempt to close multiple times (yet those could have breaking changes so I won't make either request).

Thanks for taking a look at this.

**Comment by kayabaNerve** [comment]
This can no longer be efficiently tested due to how the chronos branch updates IP handling. That said, I'm confident the above commit fixes it to the point I'm willing to close this. We'll know for sure after the next network. If the problem still exists, we can reopen this issue.

**Comment by dom96** [comment]
@kayabaNerve are you sure that exception get's thrown by `accept`?

What looks suspect to me is the `asyncCheck`. Keep in mind what `asyncCheck` does, it does re-throw whatever exception is thrown and because the async dispatcher runs it you can only catch it there. If you want to handle these sorts of errors then create a custom `asyncCheck` proc (it's just setting a callback which re-throws, see it's implementation), should be easy to do.

**Comment by kayabaNerve** [comment]
Considering that `accept` has an `await`, and it's the function which handles `accept`'s return value which is `asyncCheck`, and `accept` never throws due to a setBlocking -> fnctl call, I'm quite sure. Again:

```
/home/lukep/Meros/src/Meros.nim(37) Meros
/home/lukep/Meros/src/Meros.nim(32) main
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncdispatch.nim(1874) runForever
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncdispatch.nim(1569) poll
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncdispatch.nim(1335) runOnce
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncdispatch.nim(210) processPendingCallbacks
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncfutures.nim(297) :anonymous
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncnet.nim(462) :anonymous
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncnet.nim(146) newAsyncSocket
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/nativesockets.nim(579) setBlocking
/home/lukep/.choosenim/toolchains/nim-1.0.4/lib/pure/includes/oserr.nim(94) raiseOSError
Error: unhandled exception: Bad file descriptor [OSError]
```

**Comment by dom96** [comment]
I don't know how that line of code is transformed, but since you're nesting these calls so much it might be quite surprising. I would break that out and not use ``asyncCheck`` to be sure. The `processPendingCallbacks` is what suggests to me that `asyncCheck` is failing, but again, you can verify this by adding some debug code into `asyncCheck`.

It would be really helpful if you could test this, because if exceptions are being lost to the event loop like this then we have a pretty major problem in the async implementation.
