### ISSUE TITLE
Spawning the GUI on a system without a DE causes a segfault.

### ISSUE THREAD

**Issue by kayabaNerve** [MerosCrypto/Meros#184]
This is avoided by either using `-d:nogui` when compiling or running with `--no-gui`/`-ng`. That said, we should never segfault, for safety, and beyond that, provide a helpful note about using `--no-gui`.

**Comment by Crypto-SI** [comment]
Between this and issue #194 there is the usage of Acryonym/shortening that is somewhat unneeded. I'm assuming by DE you mean Desktop Environment?

**Comment by kayabaNerve** [comment]
While I agree for LE/BE, as the only context I gave was networking, I disagree in this case. DE does refer to Desktop Environment, and with the context of "GUI" and "segfault", I believe it's a perfectly valid leap. While non-developers likely won't understand the issue, non-developers also won't have a system without a Desktop Environment or know what a segfault is.

The only time this could be user facing is with a VPS. That said, while those are being used for testnets, we already provide extensive support in Discord instead of referring to the issue tracker. They're also "Developer" Testnets. When we have "Testnets", and we provide binaries, we'll provide both a "meros" and "merosd" binary, the latter being for servers and not containing a GUI at all. "d" stands for daemon and is a standard suffix for server binaries (with the appropriate functionality).

Beyond that, this is easy enough to fix, taking ~10 minutes. It's literally an if check on the function which spawns the GUI. I don't expect it to be around log enough to annoy any users. That said, to ensure it isn't, I'll add it to the milestone.
