### ISSUE TITLE
Meros should use LE instead of BE.

### ISSUE THREAD

**Issue by kayabaNerve** [MerosCrypto/Meros#194]
I personally despise LE, yet I acknowledge it as the standard for network protocols.

**Comment by Crypto-SI** [comment]
Why?

**Comment by kayabaNerve** [comment]
LE and BE stand for Little and Big Endian. They're two different ways to store numbers in computers. If you have the number 100, BE (effectively; simplified explanation) stores 1 0 0. LE stores 0 0 1. I prefer BE due to the similarities to the traditional number system, yet LE is what's become the accepted standard. We shouldn't break off from usual usage solely to satisfy personal preference. It will make debugging the network messages a bit more annoying, but I believe it's worth it in the long run.
