### ISSUE TITLE
Setting data-dir with absolute path fails with OSError

### ISSUE THREAD

**Issue by jerrosenberg** [MerosCrypto/Meros#256]
Running:
`./Meros --data-dir /var/local/Meros`

Results in:
```
/usr/local/src/Meros/Meros/src/Meros.nim(22) Meros
/usr/local/src/Meros/Meros/src/objects/ConfigObj.nim(311) newConfig
/nim/lib/system/assertions.nim(29) failedAssertImpl
/nim/lib/system/assertions.nim(22) raiseAssert
/nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: /usr/local/src/Meros/Meros/src/objects/ConfigObj.nim(311, 13) `false` Couldn't create 
the data directory due to an OSError: No such file or directory [AssertionError]
```

Running this works fine:
`./Meros --data-dir "../../../../var/local/Meros"`

**Comment by kayabaNerve** [comment]
Are you missing a `../`? One to Meros, one to src, one to local, one to usr. That ends up as `/usr/var/local/Meros`, no?

**Comment by jerrosenberg** [comment]
No, my working directory is `/usr/local/bin/meros/`. The issue is not for running with the relative path. It's failing on the absolute path.

**Comment by jerrosenberg** [comment]
The culprit is here I believe: https://github.com/MerosCrypto/Meros/blob/master/src/objects/ConfigObj.nim#L307-L309

For an absolute path the first segment of the split is empty string.

**Comment by kayabaNerve** [comment]
Got it. I was confused about your working directory so I just wanted to rule that out.

Good catch :) Thanks for doing my work for me. I'll push out a fix before the net today.

**Comment by kayabaNerve** [comment]
@jerrosenberg Fixed! Thank you again for reporting this.
