### ISSUE TITLE
Disallowing spending unverified transactions doesn't meet the protocol

### ISSUE THREAD

**Issue by PlasmaPower** [MerosCrypto/Meros#84]
If transaction B spends the output of transaction A, according to the protocol, both may be archived in the same block before either is verified (verifications will be archived in later blocks). However, the current node won't accept this block as transaction B spends transaction A before it's verified.

IMO disallowing spending unverified transactions doesn't make sense, as verification should be a layer on top of transactions.

**Comment by kayabaNerve** [comment]
I believe this is a bug, and as it would cause a hard fork, it is critical. That said, I feel like I thought about this and handled it...

Marking as critical for now and will write a test to find out once MeritRemovals are merged.
